// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH07m7Qsv7ohnY5Y9HK8sPmP4tqw0FSNs',
    appId: '1:634728943742:web:aabf3752ea1687c698482f',
    messagingSenderId: '634728943742',
    projectId: 'clubconnect-8be79',
    authDomain: 'clubconnect-8be79.firebaseapp.com',
    storageBucket: 'clubconnect-8be79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQuSjglmWOrQTFfnpZ-4YirNrRIZl6ooo',
    appId: '1:634728943742:android:bc2ce3ee1953be4c98482f',
    messagingSenderId: '634728943742',
    projectId: 'clubconnect-8be79',
    storageBucket: 'clubconnect-8be79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBanUipxGkyzg0M3avII9_Gzp_SDITyYoQ',
    appId: '1:634728943742:ios:a41d4eb3d245431f98482f',
    messagingSenderId: '634728943742',
    projectId: 'clubconnect-8be79',
    storageBucket: 'clubconnect-8be79.firebasestorage.app',
    iosBundleId: 'com.example.clubConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBanUipxGkyzg0M3avII9_Gzp_SDITyYoQ',
    appId: '1:634728943742:ios:a41d4eb3d245431f98482f',
    messagingSenderId: '634728943742',
    projectId: 'clubconnect-8be79',
    storageBucket: 'clubconnect-8be79.firebasestorage.app',
    iosBundleId: 'com.example.clubConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH07m7Qsv7ohnY5Y9HK8sPmP4tqw0FSNs',
    appId: '1:634728943742:web:18f8c29543d74f9398482f',
    messagingSenderId: '634728943742',
    projectId: 'clubconnect-8be79',
    authDomain: 'clubconnect-8be79.firebaseapp.com',
    storageBucket: 'clubconnect-8be79.firebasestorage.app',
  );
}
